#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
# Requirements: Accepts 4 parameters, path, IP, username, SSH private key
# sould Display message if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
