#!/usr/bin/env bash
# should install Web servers
# Requirements: Install nginx, listening on port 80, using curl, use systemctl

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
