#!/usr/bin/env bash
# should install Web servers
# Requirements: Install nginx, listening on port 80, using curl, use systemctl

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx start
