#!/usr/bin/env bash
# shellcheck disable=SC2154
# should create new nginx server

# update os
sudo apt-get update
# should install nginx
sudo apt-get install nginx -y

# should create html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# should move permanently redirect (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# should redirect to 404 error page
echo "page not found" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# should return an HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# syntax errors
sudo nginx -t

# should restart nginx when change happened
sudo service nginx restart
