#!/usr/bin/env bash
# should print numbers
#   should print "Fizz" when the multiple is 3
#   should print "Buzz" when the multiple is 5
#   Otherwise, displays the number.

for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
