#!/usr/bin/env bash
# should changes domain resolve ips

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root. Please use 'sudo'."
    exit 1
fi

local="127.0.0.2 localhost"
url="8.8.8.8 facebook.com"

echo "$local" >> /etc/hosts
echo "$url" >> /etc/hosts

if grep -q "$local" /etc/hosts && grep -q "$url" /etc/hosts; then
    echo "changed:"
    cat /etc/hosts
else
    echo "error"
    exit 1
fi

exit 0
