#!/usr/bin/env bash
# should listening to local host on port 98

nc -l -p 98

while true; do
  (echo -ne "HTTP/1.1 200 OK\r\nContent-Length: $(echo -n "Hello world n\\test" | wc -c)\r\n\r\nHello world") | nc -l -p 98 -q 1
done
