#!/usr/bin/env bash

# should return list of Gunicorn process ids
gunicorn_pids=$(pgrep gunicorn)

if [ -z "$gunicorn_pids" ]; then
    echo "No Gunicorn processes found."
    exit 1
fi

# should kill workers ports
echo "Stopping old workers gracefully..."
for pid in $gunicorn_pids; do
    kill -HUP "$pid"
done

# should wait workers to finish processing
echo "Waiting for old workers to finish processing..."
sleep 5

echo "Graceful reload complete"
