#!/usr/bin/env bash
# should write a Bash script that uses ssh to connect to your server using
# the private key ~/.ssh/school with the user ubuntu
# Requirements: Only use ssh, cannot use -l, no need to handle private key

ssh ubuntu -i ~/.ssh/school
